// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChangoMasAPI.Models;

public partial class CarritoProducto
{
    public int IdCarrito { get; set; }

    public int IdProducto { get; set; }

    public int Cantidad { get; set; }

    public virtual Carrito IdCarritoNavigation { get; set; }

    public virtual Producto IdProductoNavigation { get; set; }
}