// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChangoMasAPI.Models;

public partial class Usuario
{
    public int IdUsuario { get; set; }

    public string NombreCompleto { get; set; }

    public string Email { get; set; }

    public string Contraseña { get; set; }

    public string Provincia { get; set; }

    public string Ciudad { get; set; }

    public string Calle { get; set; }

    public string CodigoPostal { get; set; }

    public string NumeroCalle { get; set; }

    public string Departamento { get; set; }

    public int IdRol { get; set; }

    public virtual ICollection<Carrito> Carritos { get; set; } = new List<Carrito>();

    public virtual Rol IdRolNavigation { get; set; }
}